---
- name: touch a windows host   # JUST a name
  hosts: windows         # group name from inventory
  connection: winrm      # use to connect to windows host
  gather_facts: true     # no facts needed

  tasks:

    # CHOCOLATEY.CHOCOLATEY.WIN_CHOCOLATEY
    - name: install multiple packages
      chocolatey.chocolatey.win_chocolatey:
        name:
        - git
        - putty
        - adobereader
        state: present

